name: v_chat_one_signal
description: v chat one signal push notifications implementations for flutter apps for android and ios
version: 1.2.1
homepage: ^1.3.0
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk
publish_to: none
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_sdk_core:
    path: ../v_chat_sdk_core
  onesignal_flutter: ^5.3.0
  eraser: ^3.0.0
  app_badge_plus: ^1.2.1
  http: ^1.3.0
  v_platform: ^2.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
