// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN49HP76JL7o1drQwvYcv8SG1s76UuXSM',
    appId: '1:810218634692:web:ff8bb4a5e0552a2f4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    authDomain: 'super-up-27b67.firebaseapp.com',
    storageBucket: 'super-up-27b67.firebasestorage.app',
    measurementId: 'G-F2Z2THB0CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPH2-5XPakHokRigJy-G0MlaRlzGHee8',
    appId: '1:810218634692:android:683435a08ca439244db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAPTRWBm1CELHaf-9uVmepRwSXXwcqzU',
    appId: '1:810218634692:ios:e9221ff05d45855e4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.firebasestorage.app',
    iosBundleId: 'com.superup.otp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAPTRWBm1CELHaf-9uVmepRwSXXwcqzU',
    appId: '1:810218634692:ios:e9221ff05d45855e4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.firebasestorage.app',
    iosBundleId: 'com.superup.otp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA49_BHAHffgEbS_mtGopFjwYpLtM7v638',
    appId: '1:810218634692:web:4e5dace8b4de8c344db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    authDomain: 'super-up-27b67.firebaseapp.com',
    storageBucket: 'super-up-27b67.firebasestorage.app',
    measurementId: 'G-1D0VJLPNWT',
  );

}