name: v_chat_sdk_core
description: core package for v chat sdk witch use socket.io with node js and mongodb db
version: 1.1.0
homepage: ^1.3.0
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/tree/master/core_packages/v_chat_sdk_core
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.3.0
  logging: ^1.3.0
  chopper: ^8.1.0
  http_parser: ^4.1.2
  encrypt: 5.0.1
  crypto: ^3.0.6
  socket_io_client: ^3.1.2
  latlong2: ^0.9.1
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5

  sqlite3_flutter_libs: ^0.5.32
  diacritic: ^0.1.6
  flutter_fgbg: ^0.7.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  google_api_availability: ^5.0.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.4.0
  event_bus_plus:
    git:
      url: https://github.com/AndrewPiterov/event_bus_plus.git
      ref: refs/pull/9/head
  uuid: ^4.5.1
  collection: ^1.19.1
  v_platform: ^2.1.4
  timeago: ^3.7.0
  flutter_parsed_text: ^2.2.1
  background_downloader: ^9.2.1
  super_up_core:
    path: ../super_up_core
  platform_local_notifications:
    path: ../platform_local_notifications
  enum_to_string: ^2.2.1
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  flutter_callkit_incoming:
    git:
      url: https://github.com/hatemragab/flutter_callkit_incoming.git
      ref: dev
  bson: ^5.0.7
dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  lints: ^5.1.1
  flutter_lints: ^5.0.0
flutter:
platforms:
  android:
  ios:
  web:
  windows:
  macos:
