// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN49HP76JL7o1drQwvYcv8SG1s76UuXSM',
    appId: '1:810218634692:web:ff8bb4a5e0552a2f4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    authDomain: 'super-up-27b67.firebaseapp.com',
    storageBucket: 'super-up-27b67.appspot.com',
    measurementId: 'G-F2Z2THB0CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPH2-5XPakHokRigJy-G0MlaRlzGHee8',
    appId: '1:810218634692:android:cb9ab785448cf39c4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAPTRWBm1CELHaf-9uVmepRwSXXwcqzU',
    appId: '1:810218634692:ios:5dded0a69cfc23ad4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.appspot.com',
    iosClientId:
        '810218634692-afum8ah88qhpv7g3sda00mriitqg28h3.apps.googleusercontent.com',
    iosBundleId: 'com.app.superup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAPTRWBm1CELHaf-9uVmepRwSXXwcqzU',
    appId: '1:810218634692:ios:5dded0a69cfc23ad4db891',
    messagingSenderId: '810218634692',
    projectId: 'super-up-27b67',
    storageBucket: 'super-up-27b67.appspot.com',
    iosClientId:
        '810218634692-afum8ah88qhpv7g3sda00mriitqg28h3.apps.googleusercontent.com',
    iosBundleId: 'com.app.superup',
  );
}
